NODE_INDEX=1 \
NUM_NODES=5 \
IP_ADDR=192.168.0.3 \
URL=http://${IP_ADDR} \
PORT=300${NODE_INDEX} \
IS_BOOTSTRAP=false \
BOOTSTRAP_URL=http://192.168.0.2 \
BOOTSTRAP_PORT=3000 \
DIFFICULTY=4 \
BLOCK_CAPACITY=5 \
PASSPHRASE=nb-key-${NODE_INDEX} \

sudo docker run -it --init \
    -p ${PORT}:${PORT} \
    -e NODE_INDEX=${NODE_INDEX} \
    -e NUM_NODES=${NUM_NODES} \
    -e IS_BOOTSTRAP=${IS_BOOTSTRAP} \
    -e BOOTSTRAP_URL=${BOOTSTRAP_URL} \
    -e BOOTSTRAP_PORT=${BOOTSTRAP_PORT} \
    -e DIFFICULTY=${DIFFICULTY} \
    -e BLOCK_CAPACITY=${BLOCK_CAPACITY} \
    -e PASSPHRASE=${PASSPHRASE} \
    -e URL=${URL} \
    -e PORT=${PORT} \
    giorgosstef/nb-backend:dist